=== csukaj/ots-api/app/Services/Billing/Szamlazzhu/storno/xmlszamlast.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.szamlazz.hu/xmlszamlast" xmlns:tns="http://www.szamlazz.hu/xmlszamlast" elementFormDefault="qualified">
    <complexType name="vevoTipus">
        <sequence>
            <element name="email" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="eladoTipus">
        <sequence>
            <element name="emailReplyto" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailTargy" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailSzoveg" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="beallitasokTipus">
        <sequence>
            <element name="felhasznalo" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="jelszo" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="eszamla" type="boolean" maxOccurs="1" minOccurs="1"></element>
            <element name="kulcstartojelszo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaLetoltes" type="boolean" maxOccurs="1" minOccurs="1"></element>
            <element name="szamlaLetoltesPld" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="aggregator" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="fejlecTipus">
        <sequence>
            <element name="szamlaszam" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="keltDatum" type="date" maxOccurs="1" minOccurs="0"></element>
            <element name="teljesitesDatum" type="date" maxOccurs="1" minOccurs="0"></element>
            <element name="tipus" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <element name="xmlszamlast">
	    <complexType>
	        <sequence>
	            <element name="beallitasok" type="tns:beallitasokTipus" maxOccurs="1" minOccurs="1"></element>
	            <element name="fejlec" type="tns:fejlecTipus" maxOccurs="1" minOccurs="1"></element>
	            <element name="elado" type="tns:eladoTipus" maxOccurs="1" minOccurs="0"></element>
	            <element name="vevo" type="tns:vevoTipus" maxOccurs="1" minOccurs="0"></element>
	        </sequence>
	    </complexType>
    </element>
</schema>

=== csukaj/ots-api/app/Services/Billing/Szamlazzhu/storno/xmlszamlast.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlszamlast xmlns="http://www.szamlazz.hu/xmlszamlast" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/xmlszamlast http://www.szamlazz.hu/docs/xsds/agentst/xmlszamlast.xsd">
  <beallitasok>
    <felhasznalo>Kérem töltse ki!</felhasznalo>
    <jelszo>Kérem töltse ki!</jelszo>
    <eszamla>false</eszamla>
    <kulcstartojelszo>Kérem töltse ki ha van, vagy hagyja üresen!</kulcstartojelszo>
    <szamlaLetoltes>true</szamlaLetoltes>
    <szamlaLetoltesPld>1</szamlaLetoltesPld>
    <aggregator></aggregator>
  </beallitasok>
  <fejlec> 
    <szamlaszam>E-TST-2011-1</szamlaszam>
    <keltDatum>2010-09-12</keltDatum>
    <teljesitesDatum>2010-09-10</teljesitesDatum>
    <tipus>SS</tipus>
  </fejlec>
  <elado>
    <emailReplyto>elado@example.com</emailReplyto>
    <emailTargy>Email tárgya</emailTargy>
    <emailSzoveg>
Ez az email szövege.
Aláírás
    </emailSzoveg>
  </elado>
  <vevo>
    <email>vevo@example.com</email>
  </vevo>
</xmlszamlast>
