=== csukaj/ots-api/app/Services/Billing/Szamlazzhu/xml/szamla/szamla.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.szamlazz.hu/szamla" xmlns:tns="http://www.szamlazz.hu/szamla" elementFormDefault="qualified">

    <simpleType name="nyelvTipus">
        <restriction base="string">
            <enumeration value="hu"></enumeration>
            <enumeration value="en"></enumeration>
            <enumeration value="de"></enumeration>
            <enumeration value="it"></enumeration>
            <enumeration value="ro"></enumeration>
            <enumeration value="sk"></enumeration>
            <enumeration value="hr"></enumeration>
            <enumeration value="fr"></enumeration>
			<enumeration value="es"></enumeration>
			<enumeration value="cz"></enumeration>
			<enumeration value="pl"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="afatipusTipus">
        <restriction base="string">
            <enumeration value="TAM"></enumeration>
            <enumeration value="AAM"></enumeration>
            <enumeration value="EU"></enumeration>
            <enumeration value="EUK"></enumeration>
            <enumeration value="MAA"></enumeration>
            <enumeration value="F.AFA"></enumeration>
            <enumeration value="K.AFA"></enumeration>
            <enumeration value="ÁKK"></enumeration>
        </restriction>
    </simpleType>
    
    <simpleType name="fizmodunifiedTipus">
        <restriction base="string">
            <enumeration value="átutalás"></enumeration>
            <enumeration value="készpénz"></enumeration>
            <enumeration value="bankkártya"></enumeration>
            <enumeration value="csekk"></enumeration>
            <enumeration value="utánvét"></enumeration>
            <enumeration value="ajándékutalvány"></enumeration>
            <enumeration value="barion"></enumeration>
            <enumeration value="barter"></enumeration>
            <enumeration value="csoportos beszedés"></enumeration>
            <enumeration value="OTP Simple"></enumeration>
            <enumeration value="kompenzáció"></enumeration>
            <enumeration value="kupon"></enumeration>
            <enumeration value="PayPal"></enumeration>
            <enumeration value="PayU"></enumeration>
            <enumeration value="SZÉP kártya"></enumeration>
            <enumeration value="utalvány"></enumeration>
            <enumeration value="egyéb"></enumeration>
        </restriction>
    </simpleType>



    <complexType name="cimTipus">
        <sequence>
            <element name="orszag"    type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="irsz"      type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="telepules" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="cim"       type="string" maxOccurs="1" minOccurs="1"></element>
        </sequence>
    </complexType>

    <complexType name="cimpostaTipus">
        <sequence>
            <element name="nev"       type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="orszag"    type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="irsz"      type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="telepules" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="cim"       type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="bankTipus">
        <sequence>
            <element name="nev"        type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="bankszamla" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <!-- szállító adatai -->
    <complexType name="szallitoTipus">
        <sequence>
            <element name="id"        type="int"               maxOccurs="1" minOccurs="1"></element>
            <element name="nev"       type="string"            maxOccurs="1" minOccurs="1"></element>
            <element name="cim"       type="tns:cimTipus"      maxOccurs="1" minOccurs="1"></element>
            <element name="postacim"  type="tns:cimTipus"      maxOccurs="1" minOccurs="0"></element>
            <element name="adoszam"   type="string"            maxOccurs="1" minOccurs="1"></element>
            <element name="adoszameu" type="string"            maxOccurs="1" minOccurs="0"></element>
            <element name="bank"      type="tns:bankTipus"     maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>


    <!-- számla alapadatai -->
    <complexType name="alapTipus">
        <sequence>
            <element name="id"            type="int"                    maxOccurs="1" minOccurs="1"></element>
            <element name="szamlaszam"    type="string"                 maxOccurs="1" minOccurs="1"></element>
            <element name="iktatoszam"    type="string"                 maxOccurs="1" minOccurs="0"></element>
            <element name="tipus"         type="string"                 maxOccurs="1" minOccurs="1"></element>
            <element name="eszamla"       type="int"                    maxOccurs="1" minOccurs="1"></element>
            <element name="hivszamlaszam" type="string"                 maxOccurs="1" minOccurs="0"></element>
            <element name="hivdijbekszam" type="string"                 maxOccurs="1" minOccurs="0"></element>
            <element name="kelt"          type="date"                   maxOccurs="1" minOccurs="1"></element>
            <element name="telj"          type="date"                   maxOccurs="1" minOccurs="1"></element>
            <element name="fizh"          type="date"                   maxOccurs="1" minOccurs="1"></element>
            <element name="fizmod"        type="string"                 maxOccurs="1" minOccurs="1"></element>
            <element name="fizmodunified" type="tns:fizmodunifiedTipus" maxOccurs="1" minOccurs="1"></element>
            <element name="rendelesszam"  type="string"                 maxOccurs="1" minOccurs="0"></element>
            <element name="nyelv"         type="tns:nyelvTipus"         maxOccurs="1" minOccurs="1"></element>
            <element name="devizanem"     type="string"                 maxOccurs="1" minOccurs="1"></element>
            <element name="devizabank"    type="string"                 maxOccurs="1" minOccurs="0"></element>
            <element name="devizaarf"     type="double"                 maxOccurs="1" minOccurs="0"></element>
            <element name="megjegyzes"    type="string"                 maxOccurs="1" minOccurs="0"></element>
            <element name="penzforg"      type="boolean"                maxOccurs="1" minOccurs="1"></element>
            <element name="kata"          type="boolean"                maxOccurs="1" minOccurs="1"></element>
            <element name="teszt"         type="boolean"                maxOccurs="1" minOccurs="1"></element>
        </sequence>
    </complexType>

    <!-- vevő adatai -->
    <complexType name="fokonyvvevoTipus">
        <sequence>
            <element name="vevo"           type="string"  maxOccurs="1" minOccurs="0"></element>
            <element name="vevoazon"       type="string"  maxOccurs="1" minOccurs="0"></element>
            <element name="datum"          type="date"    maxOccurs="1" minOccurs="0"></element>
            <element name="folyamatostelj" type="boolean" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="vevoTipus">
        <sequence>
            <element name="id"        type="int"                  maxOccurs="1" minOccurs="0"></element>
            <element name="nev"       type="string"               maxOccurs="1" minOccurs="1"></element>
            <element name="azonosito" type="string"               maxOccurs="1" minOccurs="0"></element>
            <element name="cim"       type="tns:cimTipus"         maxOccurs="1" minOccurs="1"></element>
            <element name="postacim"  type="tns:cimpostaTipus"    maxOccurs="1" minOccurs="0"></element>
            <element name="adoszam"   type="string"               maxOccurs="1" minOccurs="1"></element>
            <element name="adoszameu" type="string"               maxOccurs="1" minOccurs="0"></element>
            <element name="fokonyv"   type="tns:fokonyvvevoTipus" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <!-- számla tételek -->
    <complexType name="fokonyvtetelTipus">
        <sequence>
            <element name="arbevetel"           type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="afa"                 type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="gazdasagiesemeny"    type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="gazdasagiesemenyafa" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="elszdattol"          type="date"   maxOccurs="1" minOccurs="0"></element>
            <element name="elszdatig"           type="date"   maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="tetelTipus">
        <sequence>
            <element name="nev"              type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="azonosito"        type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="mennyiseg"        type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="mennyisegiegyseg" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="nettoegysegar"    type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="afatipus"         type="tns:afatipusTipus" maxOccurs="1" minOccurs="0"></element>
            <element name="afakulcs"         maxOccurs="1" minOccurs="1">
                <simpleType>
                    <restriction base="int">
                        <minInclusive value="0"></minInclusive>
                    </restriction>
                </simpleType>
            </element>
            <element name="netto"            type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="arresafaalap"     type="double" maxOccurs="1" minOccurs="0"></element>
            <element name="afa"              type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="brutto"           type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="megjegyzes"       type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="fokonyv"          type="tns:fokonyvtetelTipus" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="tetelekTipus">
        <sequence>
            <element name="tetel" type="tns:tetelTipus" maxOccurs="unbounded" minOccurs="1"></element>
        </sequence>
    </complexType>

    <!-- áfakulcsonkénti összesítés -->
    <complexType name="afakulcsosszTipus">
        <sequence>
            <element name="afatipus" type="tns:afatipusTipus" maxOccurs="1" minOccurs="0"></element>
            <element name="afakulcs" maxOccurs="1" minOccurs="1">
                <simpleType>
                    <restriction base="int">
                        <minInclusive value="0"></minInclusive>
                    </restriction>
                </simpleType>
            </element>
            <element name="netto"    type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="afa"      type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="brutto"   type="double" maxOccurs="1" minOccurs="1"></element>
        </sequence>
    </complexType>
    <!-- számla teljes összesítés -->
    <complexType name="totalosszTipus">
        <sequence>
            <element name="netto"  type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="afa"    type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="brutto" type="double" maxOccurs="1" minOccurs="1"></element>
        </sequence>
    </complexType>
    <!-- számla összesítők (áfakulcsonként és total) -->
    <complexType name="osszegekTipus">
        <sequence>
            <element name="afakulcsossz" type="tns:afakulcsosszTipus" maxOccurs="unbounded" minOccurs="1"></element>
            <element name="totalossz"    type="tns:totalosszTipus" maxOccurs="1" minOccurs="1"></element>
        </sequence>
    </complexType>
    
    <!-- számla kifizetettségi adatok -->
    <complexType name="kifizetesTipus">
        <sequence>
            <element name="datum"      type="date"   maxOccurs="1" minOccurs="1"></element>
            <element name="jogcim"     type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="osszeg"     type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="bankszamlaszam" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="kifizetesekTipus">
        <sequence>
            <element name="kifizetes" type="tns:kifizetesTipus" maxOccurs="5" minOccurs="1"></element>
        </sequence>
    </complexType>
    
    <!-- gyökérelem -->
    <element name="szamla">
        <complexType>
            <sequence>
                <element name="szallito"    type="tns:szallitoTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="alap"        type="tns:alapTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="vevo"        type="tns:vevoTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="tetelek"     type="tns:tetelekTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="osszegek"    type="tns:osszegekTipus" maxOccurs="1" minOccurs="1"></element>
                <element name="kifizetesek" type="tns:kifizetesekTipus" maxOccurs="1" minOccurs="0"></element>
                <element name="pdf"         type="string"                             minOccurs="0"></element>
            </sequence>
        </complexType>
    </element>
    
</schema>

=== csukaj/ots-api/app/Services/Billing/Szamlazzhu/xml/szamla/szamla.xml
<?xml version="1.0" encoding="UTF-8"?>
<szamla xmlns="http://www.szamlazz.hu/szamla" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/szamla http://www.szamlazz.hu/docs/xsds/szamla/szamla.xsd">
    <szallito>                                                             <!-- REQ         -->
        <id>12345</id>                                                     <!-- REQ int     -->
        <nev>Példa Kft.</nev>                                              <!-- REQ string  -->
        <cim>                                                              <!-- REQ         -->
            <orszag></orszag>                                              <!--     string  -->
            <irsz>1234</irsz>                                              <!-- REQ string  -->
            <telepules>Budapest</telepules>                                <!-- REQ string  -->
            <cim>Kis utca 2.</cim>                                         <!-- REQ string  --> <!-- a cím többi része -->
        </cim>
        <postacim>                                                         
            <orszag></orszag>                                              <!--     string  -->
            <irsz></irsz>                                                  <!--     string  -->
            <telepules></telepules>                                        <!--     string  -->
            <cim></cim>                                                    <!--     string  --> <!-- a cím többi része -->
        </postacim>                                                        
        <adoszam>12345678-9-99</adoszam>                                   <!-- REQ string  -->
        <adoszameu></adoszameu>                                            <!--     string  -->
        <bank>                                                             
            <nev></nev>                                                    <!--     string  -->
            <bankszamla>12345678-12345678</bankszamla>                     <!--     string  -->
        </bank>
    </szallito>
    <alap>                                                                 <!-- REQ         -->
        <id>123456</id>                                                    <!-- REQ int     --> <!-- a számla számlázz.hu-s belső azonosítója -->
        <szamlaszam>2015-123</szamlaszam>                                  <!-- REQ string  --> <!-- a számla egyedi száma -->
        <iktatoszam></iktatoszam>                                          <!--     string  --> <!-- könyvelési rendszertől kapott adat -->
        <tipus>SZ</tipus>                                                  <!-- REQ string  --> <!-- "SZ" Számla, "SS" Sztornó számla, "JS" Jóváíró számla, "HS" Helyesbítő számla, "ES" Előlegszámla, "VS" Végszámla, "D" Díjbekérő, "SL" szállítólevél -->
        <eszamla>1</eszamla>                                               <!-- REQ string  --> <!-- 0: nem számla,  1: papír számla,  2: e-számla,  3: e-számla -->
        <hivszamlaszam>2015-1</hivszamlaszam>                              <!--     string  --> <!-- Ha a számla sztornózó vagy jóváíró vagy végszámla, akkor a szülő számla számlaszáma -->
        <hivdijbekszam>D-1</hivdijbekszam>                                 <!--     string  --> <!-- Ha a számla díjbekérő alapján készült akkor a díbekérő száma -->
        <kelt>2015-12-01</kelt>                                            <!-- REQ date    --> <!-- Számla kelte     -->
        <telj>2015-12-02</telj>                                            <!-- REQ date    --> <!-- Teljesítés időpontja  -->
        <fizh>2015-12-03</fizh>                                            <!-- REQ date    --> <!-- Fizetései határidő    -->
        <fizmod>bankkártya</fizmod>                                        <!-- REQ string  --> <!-- Fizetési mód: agent esetén bármi lehet, egyébként fix értékek a felületen -->
        <fizmodunified>bankkártya</fizmodunified>                          <!-- REQ string  --> <!-- Fizetési mód: ha nem olyan a fizetési mód, mint ami a kézi számlán is elérhető, akkor "egyéb" lesz az értéke -->
        <rendelesszam></rendelesszam>                                      <!--     string  -->
        <nyelv>hu</nyelv>                                                  <!-- REQ string  --> <!-- hu/en/de/sk/it/fr/hr/ro -->
        <devizanem>EUR</devizanem>                                         <!--     string  --> <!-- üres, Ft, HUF, EUR, CHF, USD, ... -->
        <devizabank></devizabank>                                          <!--     string  -->
        <devizaarf>210</devizaarf>                                         <!--     double  -->
        <megjegyzes></megjegyzes>                                          <!--     string  -->
        <penzforg>true</penzforg>                                          <!-- REQ boolean --> <!-- true ha a számla pénzforgalmi -->
        <kata>true</kata>                                                  <!-- REQ boolean --> <!-- true ha a számla KATA-s -->
        <teszt>false</teszt>                                               <!-- REQ boolean --> <!-- Teszt vagy valós céggel küldjük az adatokat -->
    </alap>         
    <vevo>                                                                 <!-- REQ         -->
        <id>1234567</id>                                                   <!-- REQ int     -->
        <nev></nev>                                                        <!-- REQ string  -->
        <azonosito></azonosito>                                            <!--     string  --> <!-- Vevő azonosító  -->
        <cim>                                                              
            <orszag></orszag>                                              <!-- REQ string  -->
            <irsz></irsz>                                                  <!-- REQ string  -->
            <telepules></telepules>                                        <!-- REQ string  -->
            <cim></cim>                                                    <!-- REQ string  --> <!-- a cím többi része -->
        </cim>                                                             
        <postacim>                                                         
            <nev></nev>                                                    <!--     string  -->
            <orszag></orszag>                                              <!--     string  -->
            <irsz></irsz>                                                  <!--     string  -->
            <telepules></telepules>                                        <!--     string  -->
            <cim></cim>                                                    <!--     string  --> <!-- a cím többi része -->
        </postacim>                                                        
        <adoszam></adoszam>                                                
        <adoszameu></adoszameu>                                            
        <fokonyv>  
            <vevo>12345A</vevo>                                            <!--     string  --> <!--  vevői főkönyvi szám -->
            <vevoazon>12345A</vevoazon>                                    <!--     string  --> <!--  vevői főkönyvi azonosító -->
            <datum>2015-12-05</datum>                                      <!--     date    --> <!--  könyvelés dátuma -->
            <folyamatostelj>false</folyamatostelj>                         <!--     boolean --> <!--  folyamatos teljesítésű-e a számla -->
        </fokonyv>
    </vevo>
    <tetelek>                                                              <!-- REQ         -->
        <tetel>                                                            <!-- REQ         -->
            <nev>Alma</nev>                                                <!-- REQ string  -->
            <azonosito></azonosito>                                        <!--     string  -->
            <mennyiseg>2</mennyiseg>                                       <!-- REQ double  -->
            <mennyisegiegyseg>kg</mennyisegiegyseg>                        <!-- REQ string  -->
            <nettoegysegar>100.1</nettoegysegar>                           <!-- REQ double  -->
            <afatipus>ÁKK</afatipus>                                       <!--     string  --> <!--  ÁKK: áfakörön kívüli, K.AFA: különbözeti áfa, F.AFA: fordított áfa fizetés, MAA: Mentes az adó alól, EUK: EU-n kívül, EU: EU-n belül, AAM: Alanyi adómentes, TAM: Tárgyi adómentes -->
            <afakulcs>0</afakulcs>                                         <!-- REQ int     -->
            <netto>200</netto>                                             <!-- REQ double  -->
            <arresafaalap>0</arresafaalap>                                 <!-- REQ double  -->
            <afa>54</afa>                                                  <!-- REQ double  -->
            <brutto>254</brutto>                                           <!-- REQ double  -->
            <megjegyzes>zöld</megjegyzes>                                  <!--     string  -->
            <fokonyv>                                                                      
                <arbevetel>12345A</arbevetel>                              <!--     string  --> <!--  árbevétel főkönyvi szám -->
                <afa>12345A</afa>                                          <!--     string  --> <!--  ÁFA főkönyvi szám -->
                <gazdasagiesemeny>12345A</gazdasagiesemeny>                <!--     string  --> <!--  gazdasági esemény főkönyvi szám -->
                <gazdasagiesemenyafa>12345A</gazdasagiesemenyafa>          <!--     string  --> <!--  ÁFA gazdasági esemény főkönyvi szám -->
                <elszdattol>2018-01-01</elszdattol>                        <!--     date    --> <!--  A számla tétel elszámolási időszak kezdete -->
