=== csukaj/ots-api/app/Services/Billing/Szamlazzhu/nyugtavalasz/xmlnyugtavalasz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.szamlazz.hu/xmlnyugtavalasz" xmlns:tns="http://www.szamlazz.hu/xmlnyugtavalasz" elementFormDefault="qualified">

    <simpleType name="afatipusTipus">
        <restriction base="string">
            <enumeration value="TAM"></enumeration>
            <enumeration value="AAM"></enumeration>
            <enumeration value="EU"></enumeration>
            <enumeration value="EUK"></enumeration>
            <enumeration value="MAA"></enumeration>
            <enumeration value="F.AFA"></enumeration>
            <enumeration value="K.AFA"></enumeration>
            <enumeration value="ÁKK"></enumeration>
        </restriction>
    </simpleType>
    
    <simpleType name="nyugtatipusTipus">
        <restriction base="string">
            <enumeration value="NY"></enumeration>          <!-- nyugta -->
            <enumeration value="SN"></enumeration>          <!-- nyugta sztornó -->
        </restriction>
    </simpleType>


    <!-- számla alapadatai -->
    <complexType name="alapTipus">
        <all>
            <element name="id"                    type="int"                   maxOccurs="1" minOccurs="1"></element>
            <element name="hivasAzonosito"        type="string"                maxOccurs="1" minOccurs="0"></element>
            <element name="nyugtaszam"            type="string"                maxOccurs="1" minOccurs="1"></element>
            <element name="tipus"                 type="tns:nyugtatipusTipus"  maxOccurs="1" minOccurs="1"></element>
            <element name="stornozott"            type="boolean"               maxOccurs="1" minOccurs="1"></element>
            <element name="stornozottNyugtaszam"  type="string"                maxOccurs="1" minOccurs="0"></element>
            <element name="kelt"                  type="date"                  maxOccurs="1" minOccurs="1"></element>
            <element name="fizmod"                type="string"                maxOccurs="1" minOccurs="1"></element>
            <element name="penznem"               type="string"                maxOccurs="1" minOccurs="1"></element>
            <element name="devizabank"            type="string"                maxOccurs="1" minOccurs="0"></element>
            <element name="devizaarf"             type="double"                maxOccurs="1" minOccurs="0"></element>
            <element name="megjegyzes"            type="string"                maxOccurs="1" minOccurs="0"></element>
            <element name="fokonyvVevo"           type="string"                maxOccurs="1" minOccurs="0"></element>
            <element name="teszt"                 type="boolean"               maxOccurs="1" minOccurs="1"></element>
        </all>
    </complexType>
    
    <!-- számla tételek -->
    <complexType name="fokonyvtetelTipus">
        <all>
            <element name="arbevetel"             type="string"                maxOccurs="1" minOccurs="0"></element>
            <element name="afa"                   type="string"                maxOccurs="1" minOccurs="0"></element>
        </all>
    </complexType>
    <complexType name="tetelTipus">
        <all>
            <element name="megnevezes"            type="string"                maxOccurs="1" minOccurs="1"></element>
            <element name="azonosito"             type="string"                maxOccurs="1" minOccurs="0"></element>
            <element name="nettoEgysegar"         type="double"                maxOccurs="1" minOccurs="1"></element>
            <element name="mennyiseg"             type="double"                maxOccurs="1" minOccurs="1"></element>
            <element name="mennyisegiEgyseg"      type="string"                maxOccurs="1" minOccurs="1"></element>
            <element name="netto"                 type="double"                maxOccurs="1" minOccurs="1"></element>
            <element name="afatipus"              type="tns:afatipusTipus"     maxOccurs="1" minOccurs="0"></element>
            <element name="afakulcs"                                           maxOccurs="1" minOccurs="1">
                <simpleType>
                    <restriction base="int">
                        <minInclusive value="0"></minInclusive>
                    </restriction>
                </simpleType>
            </element>
            <element name="afa"                   type="double"                maxOccurs="1" minOccurs="1"></element>
            <element name="brutto"                type="double"                maxOccurs="1" minOccurs="1"></element>
            <element name="fokonyv"               type="tns:fokonyvtetelTipus" maxOccurs="1" minOccurs="0"></element>
        </all>
    </complexType>
    <complexType name="tetelekTipus">
        <sequence>
            <element name="tetel"                 type="tns:tetelTipus"        maxOccurs="unbounded" minOccurs="1"></element>
        </sequence>
    </complexType>

    <!-- áfakulcsonkénti összesítés -->
    <complexType name="afakulcsosszTipus">
        <all>
            <element name="afatipus"              type="tns:afatipusTipus"     maxOccurs="1" minOccurs="0"></element>
            <element name="afakulcs"                                           maxOccurs="1" minOccurs="1">
                <simpleType>
                    <restriction base="int">
                        <minInclusive value="0"></minInclusive>
                    </restriction>
                </simpleType>
            </element>
            <element name="netto"                 type="double"                maxOccurs="1" minOccurs="1"></element>
            <element name="afa"                   type="double"                maxOccurs="1" minOccurs="1"></element>
            <element name="brutto"                type="double"                maxOccurs="1" minOccurs="1"></element>
        </all>
    </complexType>
    <!-- számla teljes összesítés -->
    <complexType name="totalosszTipus">
        <all>
            <element name="netto"                 type="double"                maxOccurs="1" minOccurs="1"></element>
            <element name="afa"                   type="double"                maxOccurs="1" minOccurs="1"></element>
            <element name="brutto"                type="double"                maxOccurs="1" minOccurs="1"></element>
        </all>
    </complexType>
    <!-- számla összesítők (áfakulcsonként és total) -->
    <complexType name="osszegekTipus">
        <sequence>
            <element name="afakulcsossz"          type="tns:afakulcsosszTipus" maxOccurs="unbounded" minOccurs="1"></element>
            <element name="totalossz"             type="tns:totalosszTipus"    maxOccurs="1" minOccurs="1"></element>
        </sequence>
    </complexType>

    <!-- jóváírások -->
    <complexType name="kifizetesTipus">
        <all>
            <element name="fizetoeszkoz"          type="string"               maxOccurs="1" minOccurs="1"></element>
            <element name="osszeg"                type="double"               maxOccurs="1" minOccurs="1"></element>
            <element name="leiras"                type="string"               maxOccurs="1" minOccurs="0"></element>
        </all>
    </complexType>
    <complexType name="kifizetesekTipus">
        <sequence>
            <element name="kifizetes"             type="tns:kifizetesTipus"   maxOccurs="unbounded" minOccurs="1"></element>
        </sequence>
    </complexType>

    <complexType name="nyugtaTipus">
        <all>
            <element name="alap"                  type="tns:alapTipus"         maxOccurs="1" minOccurs="1"></element>
            <element name="tetelek"               type="tns:tetelekTipus"      maxOccurs="1" minOccurs="1"></element>
            <element name="kifizetesek"           type="tns:kifizetesekTipus"  maxOccurs="1" minOccurs="0"></element>
            <element name="osszegek"              type="tns:osszegekTipus"     maxOccurs="1" minOccurs="1"></element>
        </all>
    </complexType>

    <element name="xmlnyugtavalasz">
        <complexType>
            <all>
                <element name="sikeres"           type="boolean"               maxOccurs="1" minOccurs="1"></element>
                <element name="hibakod"           type="int"                   maxOccurs="1" minOccurs="0"></element>
                <element name="hibauzenet"        type="string"                maxOccurs="1" minOccurs="0"></element>
                <element name="nyugtaPdf"         type="string"                maxOccurs="1" minOccurs="0"></element>
                <element name="nyugta"            type="tns:nyugtaTipus"       maxOccurs="1" minOccurs="0"></element>
            </all>
        </complexType>
    </element>
</schema>

=== csukaj/ots-api/app/Services/Billing/Szamlazzhu/nyugtavalasz/xmlnyugtavalasz.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlnyugtavalasz xmlns="http://www.szamlazz.hu/xmlnyugtavalasz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/xmlnyugtavalasz http://www.szamlazz.hu/docs/xsds/nyugta/xmlnyugtavalasz.xsd">
  <sikeres>true</sikeres>                                                <!-- REQ boolean -->
  <hibakod></hibakod>                                                    <!--     string  --> <!-- hiba esetén a hibakód -->
  <hibauzenet></hibauzenet>                                              <!--     string  --> <!-- hiba esetén a hibaüzenet -->

  <nyugtaPdf>...</nyugtaPdf>                                             <!--     string  --> <!-- nyugta PDF base64 enkódolással -->
  
  <nyugta>                                                               <!-- REQ         -->
    <alap>                                                               <!-- REQ         -->
      <id>123456</id>                                                    <!-- REQ id      -->
      <hivasAzonosito></hivasAzonosito>                                  <!--     string  --> <!-- ha meg volt adva a nyugta létrehozásakor akkor a nyugta hívásazonosítója -->
      <nyugtaszam>NYGT-2017-123</nyugtaszam>                             <!-- REQ string  -->
      <tipus>NY</tipus>                                                  <!-- REQ string  --> <!-- Nyugta típusa: NY esetén "Nyugta", SN esetén "Nyugta sztornó" -->
      <stornozott>false</stornozott>                                     <!-- REQ boolean --> <!-- true ha a nyugta stornózott, false egyébként (NY típus esetén érdekes) -->
      <stornozottNyugtaszam>NYGT-2017-100</stornozottNyugtaszam>         <!--     string  --> <!-- Ha a nyugta sztornózó, akkor a sztornózott számla száma (SN típus esetén jelzi melyik nyugta lett sztornózva) -->
      <kelt>2015-12-01</kelt>                                            <!-- REQ date    --> <!-- Nyugta kelte -->
      <fizmod>készpénz</fizmod>                                          <!-- REQ string  -->
      <penznem>EUR</penznem>                                             <!-- REQ string  --> <!-- üres, Ft, HUF, EUR, CHF, USD, ... -->
      <devizabank></devizabank>                                          <!--     string  -->
      <devizaarf>210</devizaarf>                                         <!--     double  -->
      <megjegyzes></megjegyzes>                                          <!--     string  -->
      <fokonyvVevo></fokonyvVevo>                                        <!--     string  --> <!-- könyvelési információ -->
      <teszt>false</teszt>                                               <!-- REQ boolean --> <!-- Teszt vagy valós céggel lett létrehozva a nyugta -->
    </alap>
    
    <tetelek>
      <tetel>
        <azonosito></azonosito>                                          <!--     string  --> <!-- tétel azonosítója -->
        <megnevezes>Kiscicás lábtörlő</megnevezes>                       <!-- REQ string  --> <!-- tétel megnevezése -->
        <mennyiseg>2.0</mennyiseg>                                       <!-- REQ double  --> <!-- tétel mennyisége -->
        <mennyisegiEgyseg>db</mennyisegiEgyseg>                          <!-- REQ string  --> <!-- tétel mennyiségi egysége -->
        <nettoEgysegar>10000</nettoEgysegar>                             <!-- REQ double  --> <!-- tétel nettó egységár -->
        <netto>20000.0</netto>                                           <!-- REQ double  --> <!-- tétel nettó érték (egységár * mennyiség) -->
        <afakulcs>27</afakulcs>                                          <!-- REQ double  --> <!-- áfakulcs -->
        <afa>5400.0</afa>                                                <!-- REQ double  --> <!-- áfa értéke -->
        <brutto>25400.0</brutto>                                         <!-- REQ double  --> <!-- bruttó érték -->
        <fokonyv>                                                        <!--             --> <!-- tétel főkönyvi információk -->
          <arbevetel></arbevetel>                                        <!--     string  --> <!-- árbevétel főkönyvi száma -->
          <afa></afa>                                                    <!--     string  --> <!-- áfa főkönyvi száma -->
        </fokonyv>
      </tetel>
      <tetel>
        <megnevezes>Kiskutyás lábtörlő</megnevezes>
        <mennyiseg>2.0</mennyiseg>
        <mennyisegiEgyseg>db</mennyisegiEgyseg>
        <nettoEgysegar>10000</nettoEgysegar>
        <nettoErtek>20000.0</nettoErtek>
        <afakulcs>27</afakulcs>
        <afaErtek>5400.0</afaErtek>
        <bruttoErtek>25400.0</bruttoErtek>
      </tetel>
    </tetelek>
  
    <kifizetesek>
      <kifizetes>
        <fizetoeszkoz>utalvány</fizetoeszkoz>
        <osszeg>1000.0</osszeg>
        <leiras>OTP SZÉP kártya</leiras>
      </kifizetes>
      <kifizetes>
        <fizetoeszkoz>bankkártya</fizetoeszkoz>
        <osszeg>3000.0</osszeg>
      </kifizetes>
    </kifizetesek>
  
    <osszegek>
      <afakulcsossz>                                                     <!-- REQ int     -->
        <afatipus>ÁKK</afatipus>                                         <!--     string  --> <!--  ÁKK: áfakörön kívüli, K.AFA: különbözeti áfa, F.AFA: fordított áfa fizetés, MAA: Mentes az adó alól, EUK: EU-n kívül, EU: EU-n belül, AAM: Alanyi adómentes, TAM: Tárgyi adómentes -->
        <afakulcs>0</afakulcs>                                           <!-- REQ double  -->
        <netto>200</netto>                                               <!-- REQ double  -->
        <afa>54</afa>                                                    <!-- REQ double  -->
        <brutto>254</brutto>                                             <!-- REQ double  -->
      </afakulcsossz>
      <totalossz>                                                        <!-- REQ         -->
        <netto>200</netto>                                               <!-- REQ double  -->
        <afa>54</afa>                                                    <!-- REQ double  -->
        <brutto>254</brutto>                                             <!-- REQ double  -->
      </totalossz>
    </osszegek>
  </nyugta>

</xmlnyugtavalasz>
